### ISSUE TITLE
Item Animations

### ISSUE THREAD

**Issue by PawlicaWeb** [asamy/forgottenmapeditor#20]
There's problem with showing items on map. They are animated only on first two zoom levels (16, 24), but they should be animated also on default zoom level (32).

**Comment by asamy** [comment]
That's quite odd, might be a limitation, i'll look into it.

**Comment by PawlicaWeb** [comment]
I've found similar bug, I think it's related. When you use setShowZones / setShowZone functions on zoom levels other than first two, showing of zones Isn't updated. You have to zoom in/out/move map in order to update it.

**Comment by asamy** [comment]
I can't reproduce this bug, It's working fine for me:
![screenshot](http://i.imgur.com/bWR3eKF.png)
Zoomed from 16 to like 128

This is the code I used to reproduce:
in modules/mapeditor_interface/interface.lua in function updateZoom():

``` lua
if delta then
  zoomLevel = ...
  g_map.setShowZones(not g_map.showZones())
end
```

**Comment by asamy** [comment]
This is kept for near views only for performance reasons, e.g. 2048x2048 will cause million loops which will cause a lot of freezes on low-end pcs.
