### ISSUE TITLE
Zones

### ISSUE THREAD

**Issue by PawlicaWeb** [asamy/forgottenmapeditor#21]
Hello,
Here are some of my suggestions for zones:
- Zone color should be only applied to grounds and walls
- Opacity of zone color should be set to ~25-50%

Also some new functions for them will be useful:
- g_map.getZones(pos)
- g_map.setZone(zoneId, pos)
- g_map.removeZone(zoneId, pos)
- UIMap:toggleShowingZones()
- UIMap:toggleShowindZone(id)

**Comment by asamy** [comment]
Thanks|!  Good suggestions, i'll implement them ASAP in otclient and will update this issue.

**Comment by asamy** [comment]
- g_map.getZones(pos)
- g_map.setZone(zoneId, pos)
- g_map.removeZone(zoneId, pos)

These functions can already be accessed via tile, e.g.:

```
local tile = g_map.getTile(pos)
local flags = tile:getFlags()
... test flags for bits like TILESTATE_PROTECTIONZONE etc...
... and then set the flags desired with tile:setFlags() or tile:setFlag() ...
```

Do also note, that tile:setFlags() may require that you know the flags the tile has first, so be careful, you may overwrite flags.
- UIMap::toggleShowZones()

This cannot be done using UIMap, instead, I have made it using g_map, also with new functions:
- g_map.setShowZones(bool show)
- g_map.setShowZone(tileflags_t flag, bool show)
- g_map.setZoneColor(tileflags)         -- color to show for zone
- g_map.setZoneOpacity(opacity)      -- from 0.0 to 1.0 (0.0 = full opaque, 1.0 = full transparent)

And their respective get's, but for show zones, you have:
- g_map.showZones() - test if showing zones
- g_map.showZone(tileflags) - test if showing any color for a tileflag.

**Comment by asamy** [comment]
OTClient's upstream commit https://github.com/edubart/otclient/commit/5eabf6f5189d0aa70441f6434f14bb29b8008686 implements all of these.
If there are more issues, make new issue, closing this.
