### ISSUE TITLE
Needed functions

### ISSUE THREAD

**Issue by PawlicaWeb** [asamy/forgottenmapeditor#30]
Hello,
I think that some new functions will be needed:
- UIMap:move(x, y) - function for moving map in x and y axis by certain amount of pixels. Now there's only 'setCameraPosition' function that isn't too smooth.
- Functions for drawing ghosted items on map tiles, useful for brushes :-)
  Example from RME:
  http://i.imgur.com/0MUMtmz.png

**Comment by asamy** [comment]
- UIMap::move(x, y) moving by pixels? like if you were to move to the right you would call UIMap::move(32, 0) ?

g_map.beginGhostMode()
.. do the rendering ... 
g_map.endGhostMode()

Is OK?

**Comment by PawlicaWeb** [comment]
Yeah, something like that, for example: move(32, 0) for moving right, move(-14, 0) for moving left etc.
I think that ghost functions will be ok. :-)

**Comment by asamy** [comment]
move(-14, 0) ? well, tibia sprites are all 32x32, so 14 pixels is like moving half the tile on the left.  Maybe I misunderstood something, mind explaining further?

**Comment by PawlicaWeb** [comment]
You've misunderstood me. ~16 pixels isn't like moving half the tile on the left, tiles on the map can have 8, 16, 32, 64 etc. pixels (depending on the actual zoom level).
For example: http://i.imgur.com/jk84bJW.png

This function should be useful, cause moving by one tile by 'setCameraPosition' function isn't too smooth or is too fast on some zool levels. Also it'll allow to make moving around the map more precise.

**Comment by asamy** [comment]
Alright, so, here's the ghost functions prototype:
- g_map.beginGhostMode(float opacity)
- g_map.endGhostMode()

opacity:
- 0.0 = full transparent
- 1.0 = full opaque
- 0.5 maybe that's what you would pass.

**Comment by asamy** [comment]
OTClient's upstream commit https://github.com/edubart/otclient/commit/56d6ef6642dfa10ada0f71cff7df6d0058540731 implements the needed functions.
