### ISSUE TITLE
Item search functions

### ISSUE THREAD

**Issue by PawlicaWeb** [asamy/forgottenmapeditor#32]
Hello,
I'm planning to start working on Search Widget soon, but I found out that there are two missing functions for it:
- findItemTypesByName - I know that there's already 'findItemTypeByName' function, but what if there are more items with the same name (for ex. wooden chair)?
- findItemTypesByString - useful function for autocomplete feature, for ex. findItemTypesByString('cha') will return all items with 'cha' in name.

**Comment by asamy** [comment]
Do you want a regex/wildcard search also?

**Comment by PawlicaWeb** [comment]
No, I think it won't be needed.

**Comment by asamy** [comment]
Hmm, looks like I'm going to convert the ItemType list to be a hashmap, since the auto completion function would be slow.  (Will do that later though)

Testing compilation and i'll commit the changes.

**Comment by asamy** [comment]
OTClient's upstream commit https://github.com/edubart/otclient/commit/3db8f54aa9c381a0e24479c9e4ee25ca54006d46 implements both.
