### ISSUE TITLE
Shift Spread, Scrolling, and More (Issues, Bugs, Features)

### ISSUE THREAD

**Issue by Dark199** [asamy/forgottenmapeditor#38]
A lot of features that RME has needs to be implemented onto here. 
- [x] Being able to move around the map with middle mouse button smoother,
- [x] holding shift and putting a large area of something down, 
- [x] the ability to change the lists to look like RME's Raw Pallete, 
- [x] enable or disable animations
- [x] smoother removing abilities
- [x] being able to scroll up and down in a pallete
- [x] the pallete title should always be seen as to not loose what you're currently using
- [x] having 'others' as a fail safe to see every item,
- [ ] jump to brush option,
- [x] the ability for anyone to create their own palletes, 
- [ ] items such as doors replacing floors should be fixed.
- [x] ground floors shouldn't stack
- [x] able to modify items ( changing the action id, and other options )
- [ ] framerate issues from simply trying to put down ground floors
- [x] seeing the item you're placing instead of the 'drop cursor'
- [x] having a more zoomed in area without causing the sprites to mess up (currently too zoomed out to see what a person is doing)
- [x] removal tool (right click and able to hit delete)
- [x]  'peer' ability (hovering over the item to see its name and id), 
- [x] holding mouse button shouldn't delete items already on the tile, 
- [x] whenever choosing an item it should always then go into 'pencil' mode, 
- [x] able to mass select an area by shift + holding mouse, 
- [x] items in the item pallete seem too zoomed out (they look blurry)

**Comment by comedinha** [comment]
" the ability for anyone to create their own palletes"
https://github.com/decltype/forgottenmapeditor/commit/ed41060314a861d017b2e16fa92861e535bb6320

**Comment by Dark199** [comment]
More or less extensions from RME

**Comment by asamy** [comment]
>  items such as doors replacing floors should be fixed

Is that a palette thing? I don't see that when placing doors over floors?

> able to modify items ( changing the action id, and other options 

Forgot about that, thanks for reminding me.

> FME not taking as much memory to run, framerate issues from simply trying to put down ground floors

Is that bad that it isn't taking memory?  What's your graphics card? Driver version?

> seeing the item you're placing instead of the 'drop cursor',

Hmm, will consider it.

> having a more zoomed in area without causing the sprites to mess up (currently too zoomed out to see what a person is doing),

If you don't want it to be "small", then don't zoom out?  that's the purpose of zooming out. Modify it to fit your needs in modules/mapeditor_interface/interface.lua

> removal tool (right click and able to hit delete)

You can remove items a lot easier than that, simply press CTRL and press anything you want to be deleted.

>  'peer' ability (hovering over the item to see its name and id),

You can see that in status bar.

> holding mouse button shouldn't delete items already on the tile, whenever choosing an item it should always then go into 'pencil' mode

Good idea for ease of use.

> able to mass select an area by shift + holding mouse, items in the item pallete seem too zoomed out (they look blurry)

No they're not.  They are how they are actually displayed in Tibia client.

Thanks for your contribution.  Your ideas will be kept in mind.

**P.S**: You're telling me you cannot move smoother with middle mouse button and then telling me you have lag placing items, this sounds like your graphics card/drivers are outdated.

**Side note**: Please format your bug reports in paragraphs next time, I hardly was able to read all this...  It's really annoying.

**Comment by asamy** [comment]
By the way, we're not trying to copy RME, our main aim is just to make a usable mapeditor and featurefull while being low on resources.

**Comment by Dark199** [comment]
I understand that, but some features from RME are great and would suit any map editor.

About the scrolling ability I would like to hold down the mouse button and have it moved around the area I middle mouse buttoned, instead of just holding the button in the general area you want to go.

"'peer' ability (hovering over the item to see its name and id),
You can see that in status bar."
I meant in the pallete area

By a delete tool I mean that you can select an item without going to it to 'ctrl' it.

The client on my computer to begin with runs about 450k bytes of memory. When I try to place down several floors by moving the pencil tool I get a framerate drop. 

My drivers aren't outdated; I check for updates constantly.
 And about my specifications AMD Radeon 6310, E-300 APU Radeon 1.30 GHz, with 4 GB's of ram. 

I've also been having some issue with the editor not wanting to place an item on a tile, then I having to go and find a way to make it so it is able to go on that specific tile.

Another idea; 

Ability to stack items such as tables going on top of each other.

**Comment by asamy** [comment]
> About the scrolling ability I would like to hold down the mouse button and have it moved around the area I middle mouse buttoned, instead of just holding the button in the general area you want to go.

I'll see about that.

> I meant in the pallete area

Uncomment `show-id: true` in modules/mapeditor_itempalette/itempalette.otui (There's no show-name for now).

Also, your graphics card is a low-end gfx card, we'll see about that later.

> I've also been having some issue with the editor not wanting to place an item on a tile, then I having to go and find a way to make it so it is able to go on that specific tile.

Please be a little more specific so I can reproduce the issue in my site, and therefore get it fixed.

**Comment by asamy** [comment]
Hey,

Can you please rephrase (in paragraphs) your main post? So that I can know which bugs have been fixed etc.

Thanks! :+1:

**Comment by asamy** [comment]
Thanks for doing it, I've also edited your post to tell the reader whether it's in or not.

I have not gotten explanation on this:

> items such as doors replacing floors should be fixed.

**Comment by Dark199** [comment]
I think it was because of being on 'paint' instead of 'pencil'. What is the purpose of 'paint'?

**Comment by asamy** [comment]
Paint bucket uses flood-fill algorithm to replace a set of items with another set of items (but with different id). e.g. You have a square of dirt, it can replace those dirt with sand.
We should make it so we can fill in between items.

**BTW** you can already mouse wheel on the item palette, just mouse wheel on the scrollbar itself or an empty area (e.g. not over an item).

**Comment by asamy** [comment]
I demand an explanation on "Jump to brush option", also I'm gonna mark "items such as doors replacing floors should be fixed." as nonsense if I don't get an explanation.

**Comment by asamy** [comment]
Only task is left is (besides the nonsense tasks), the selection thing.  And I'm assigning this to @Crypton33 I hope he implement this, I'll be busy the next week.

**Comment by asamy** [comment]
Closing this.  All of the bugs that make sense have been fixed.
