### ISSUE TITLE
Add support to old versions (7.6)

### ISSUE THREAD

**Issue by ronpetit** [asamy/forgottenmapeditor#39]
The map editor do not support older versions than 8.10

**Comment by asamy** [comment]
What does it fail to load? OTBM? OTB? Whaaat?

**Comment by ronpetit** [comment]
No mate, you don't understand me, it just don't have support to older client than 8.1, look

![hola](https://f.cloud.github.com/assets/5855265/1710958/25964f96-6140-11e3-832c-85d84b4e41ff.jpg)

So i can't select 7.6 version

**Comment by asamy** [comment]
Alright, here's the thing:

You can add versions by yourself in `modules/mapeditor_filebrowser/filebrowser.lua` and look for supportedVersions, add it like so:

```
local supportedVersions = {
  760, 810, 853, 854, 860, 861, 862,
  870, 910, 940, 944, 953, 954, 960,
  961, 963, 970, 971, 973, 974, 973,
  974, 975, 976, 977, 978, 979, 980,
  1010, 1022
}
```

You can add as much versions as you want but they may not work, so let me know about which ones work and which doesn't, so I can fix them.
