### ISSUE TITLE
Bug - fast mapping

### ISSUE THREAD

**Issue by PawlicaWeb** [asamy/forgottenmapeditor#40]
Hello,
This is what I get when I try to create straight line by moving the mouse quickly:
![abc](https://f.cloud.github.com/assets/5208256/1701724/ac716fa0-6069-11e3-8f4c-108474da1b08.png)
Reason? I don't know, maybe too many functions are called. Also when I do it, I get about 80-100% core usage, so I think that something needs to be optimized.

**Comment by TheSumm** [comment]
It is done like this:
g_mouse.bindAutoPress(mapWidget, handleMousePress, 50, MouseLeftButton)

It needs to be optimized.

**Comment by asamy** [comment]
This works perfectly fine for me. I don't get the bug here, is it the white thing or that it did not render everything in the line?
Are you sure that your left mouse button isn't a little bugged?

**Comment by Dark199** [comment]
I've had the same thing happen to me. It is most likely a cpu / memory usage issue.

**Comment by asamy** [comment]
It happens to me too because I accidentally release the mouse button.

**Comment by Dark199** [comment]
I can assure you it is not accidentally releasing the mouse button.

**Comment by asamy** [comment]
Okay, as Summ stated:

`g_mouse.bindAutoPress(mapWidget, handleMousePress, 50, MouseLeftButton)`

The `50` parameter is the delay, you guys might want to make it `10` and check if it goes fine for you that way.
If so, you should thank @dalkon for this.

**Comment by asamy** [comment]
`g_mouse.bindAutoPress` needs to be re-written, so i'm closing this.
