### ISSUE TITLE
Floor bug

### ISSUE THREAD

**Issue by PawlicaWeb** [asamy/forgottenmapeditor#41]
Hello,
I've found out that there is bug in viewing floors.

When I set map editor to floor 7 and focus camera in the temple, I get this:
![1](https://f.cloud.github.com/assets/5208256/1701750/5cef612e-606b-11e3-9b49-c84bc0912266.png)
But when I focus camera on a tile without upper floor, I can see the upper floors of buildings:
![2](https://f.cloud.github.com/assets/5208256/1701751/5cf27fda-606b-11e3-9772-b60ef4e4c377.png)
I think that it should be done in RME way:
![3](https://f.cloud.github.com/assets/5208256/1701757/bf4ba724-606b-11e3-81be-93b838d9b90f.png)
Only floor 7 should be seen, no matter of tile that's in the center.

**Comment by asamy** [comment]
It's not a bug, it's just how Tibia displays the map.  I also don't see how annoying it can be for a mapper, I mean, yes, it will be kind of annoying but not to the point that he'd throw his computer off his window.

**Comment by TheSumm** [comment]
I dont see a reason why this should remain in the map editor

**Comment by asamy** [comment]
Hmm, we can make it optional.  But that would require source code changes.
