### ISSUE TITLE
UIMap:movePixels bug

### ISSUE THREAD

**Issue by PawlicaWeb** [asamy/forgottenmapeditor#46]
Hello,
There's bug with movePixels function.

When I use:
movePixels(16, 0)
The map is moved by 16 pixels in right direction. But when I use that function again nothing happens. 

Also when I use movePixels(32, 0) after moving the map by 16 pixels, the map is moved by only 16 pixels.

**Comment by asamy** [comment]
Confirmed. Will look into it soon.

**Comment by asamy** [comment]
Why do we need this btw?

**Comment by asamy** [comment]
Fixed in https://github.com/edubart/otclient/commit/04515ffbb81db0b180b1bfb187531fbdaf39e7a0
