### ISSUE TITLE
Anoter UIMap:movePixels bug

### ISSUE THREAD

**Issue by PawlicaWeb** [asamy/forgottenmapeditor#51]
Hello,
I've found another bug in movePixels function. For example: I have map like this:
![pre](https://f.cloud.github.com/assets/5208256/1729395/2144309e-62c0-11e3-9779-df9a6878a18b.jpg)
It looks good, but when I use movePixels function, I get effect like this:
![aft](https://f.cloud.github.com/assets/5208256/1729400/31fc11ae-62c0-11e3-9fe0-a005bb2d606b.jpg)

**Comment by asamy** [comment]
Might be that the camera position isn't updated, I'll look into this.

**Comment by edubart** [comment]
Move pixels should **NOT** be used for more than 32 pixels, otherwise this will happen. When you want to move more than 32 pixels, you should update the camera position.

**Comment by asamy** [comment]
Fixed in https://github.com/edubart/otclient/commit/b5c3b37b3c74dfe2ba5f562db8fcb4565d52f6e7
