### ISSUE TITLE
Placing Ground On Top of Another Ground

### ISSUE THREAD

**Issue by Dark199** [asamy/forgottenmapeditor#56]
![issue one](https://f.cloud.github.com/assets/5111155/1736943/cc96b05c-636a-11e3-8783-be07f5e963f0.png)

This is the Error messages in terminal, 

![issue one part two](https://f.cloud.github.com/assets/5111155/1736954/e2432020-636a-11e3-9180-09b7059dab03.png)

This area was full of grass, and to get the wooden tile down I need to double click

**Comment by asamy** [comment]
Are you using latest OTC?  Because updateTile was bound to lua in latest commits.

Also, please use labels instead of writing manually `[Bug]`, I've edited your post this time.
