### ISSUE TITLE
Spawn related functions

### ISSUE THREAD

**Issue by PawlicaWeb** [asamy/forgottenmapeditor#68]
Hello,
I've found out that there are missing functions that could be added:

```
Spawn:getCreatures() - function that returns all creatures on spawn
g_creatures.getSpawns() - function that returns all spawns on map
```

**Comment by asamy** [comment]
Now they are added: https://github.com/edubart/otclient/commit/93be0f975f10bc84a8c520ce831b8eec3200076e

**Comment by PawlicaWeb** [comment]
Also what about:

```
g_creatures.deleteSpawn()
```

function. Is there something like it?

**Comment by asamy** [comment]
There: https://github.com/edubart/otclient/commit/e4ba805e0078bbdfe29ffa6c40a3fdd696b0a9a4
