### ISSUE TITLE
Save Error

### ISSUE THREAD

**Issue by comedinha** [asamy/forgottenmapeditor#72]
On save:
books go to under tables
not save signs
not save some uids and aids
not save map version (give error on open with rme)

**Comment by asamy** [comment]
This is abandoned until I get the feeling to work on it or the motivation to.  So if you like this project, work on the issue and maybe you'll motivate me to work on it.

**Comment by comedinha** [comment]
This project was created with the intention of being an lua alternative of a map editor, you can make millions of possibilities with it. The project can not be abandoned, pelomenos we end up with the bugs and wait until a next time.

**Comment by TheSumm** [comment]
If this cannot be abandoned then you should fix the issue.

**Comment by comedinha** [comment]
@TheSumm yes :v:

**Comment by TheSumm** [comment]
wtf yes?
That was no question.

**Comment by comedinha** [comment]
I'll try to fix this :V
