### ISSUE TITLE
10.10 support

### ISSUE THREAD

**Issue by comedinha** [asamy/forgottenmapeditor#8]
To fix 10.10 support you need add
g_game.setProtocolVersion(tonumber(currentVersion.text))
on function loadDat(f) of filebrowser
and
on start up...
g_game.setProtocolVersion(VERSION)

https://github.com/BrunoDCC/forgottenmapeditor/commit/7d1c82dd6904a947eb815a87d9ba89387105d8a2

**Comment by asamy** [comment]
Hi BrunoDCC,

I noticed you were trying to get the latest changes of my branch into yours, however, you did it wrong by just copying the changes manually, so it's better if you would use the git command:

`git pull https://github.com/allanference/forgottenmapeditor.git --rebase`

Also, I'd recommend reforking the project and adding your changes then making a pull request if you want to.
Anyways, thank you for your contributions, I've fixed that in my last commit.

**Comment by comedinha** [comment]
Ty, i am a noob in github ._
